### ISSUE TITLE
Editing is weird

### ISSUE THREAD

**Issue by tim-hilde** [Fevol/obsidian-criticmarkup#3]
https://user-images.githubusercontent.com/44113468/224373916-95874082-e865-47f0-b3a6-4bab056d844c.mov

This is the corresponding markdown file 
[Untitled.md](https://github.com/Fevol/obsidian-criticmarkup/files/10944200/Untitled.md)

**Comment by Fevol** [comment]
Many thanks for the report, the added file helped me reproduce and find the root cause of the issue! 
Problem is, while I have a fix, it makes the plugin an order of magnitude slower (0.4ms -> 4ms). 
If you want, I can create a quick build of the plugin that will not have this problem, while I look for a proper solution for the issue.

**Comment by tim-hilde** [comment]
Thanks for the quick reply. 
don't worry about creating a new release I am not reliant on the plug-in yet. Would be better to have a proper fix for it
